#include "byte_code.h"

DEFINE_ENUM(OP_CODE, OpCode, op_code)

#include "../include/get_payload_size.c"

void init_byte_code(ByteCode *byte_code)
{
    byte_code->init = NULL;
    byte_code->main = NULL;
}

void init_unit(Unit *unit)
{
    unit->parameter_count = 0;
    unit->register_count = 0;

    for (size_t i = 0; i < 128; i++)
        unit->instruction[i].word = 0x00000000;
    unit->count = 0;

    unit->nested_in = NULL;
    unit->next = NULL;
}

// TODO: Have functions of these be generated by build.py
#define GET_DATA(T)                            \
    union                                      \
    {                                          \
        T value;                               \
        uint32_t word[wordsizeof(T)];          \
        uint8_t byte[wordsizeof(T)][4];        \
    } as;                                      \
    for (size_t j = 0; j < wordsizeof(T); j++) \
        as.word[j] = unit->instruction[i++].word;

#include "../include/printf_instruction.c"

void printf_unit(Unit *unit)
{
    printf("             \x1b[04mUNIT %p\x1b[0m\n", unit);

    size_t i = 0;
    while (i < unit->count)
        i = printf_instruction(unit, i);
    printf("\n");
}

void printf_byte_code(ByteCode *byte_code)
{
    Unit *unit = byte_code->init;
    while (unit)
    {
        printf_unit(unit);
        unit = unit->next;
    }
}