// This file was generated automatically by build_program/build.py

#define OP_CODE(MACRO) \
	MACRO(OP_CALL) \
	MACRO(OP_JUMP) \
	MACRO(OP_JUMP_IF) \
	MACRO(OP_COPY) \
	MACRO(OP_COPY_DOWN) \
	MACRO(OP_COPY_UP) \
	MACRO(OP_LOAD_NONE) \
	MACRO(OP_LOAD_TRUE) \
	MACRO(OP_LOAD_FALSE) \
	MACRO(OP_LOAD_INT) \
	MACRO(OP_LOAD_NUM) \
	MACRO(OP_LOAD_STR) \
	MACRO(OP_OUT) \
	MACRO(OP_INCA) \
	MACRO(OP_DECA) \
	MACRO(OP_INCB) \
	MACRO(OP_DECB) \
	MACRO(OP_NEG) \
	MACRO(OP_NOT) \
	MACRO(OP_ADD) \
	MACRO(OP_SUB) \
	MACRO(OP_MUL) \
	MACRO(OP_DIV) \
	MACRO(OP_REM) \
	MACRO(OP_EQLA) \
	MACRO(OP_EQLN) \
	MACRO(OP_LESS) \
	MACRO(OP_LESS_EQUAL) \
	MACRO(OP_AND) \
	MACRO(OP_OR) \


