// This file was generated automatically by build_program/build.py

#define OP_CODE(MACRO) \
	MACRO(OP_CALL) \
	MACRO(OP_RUN) \
	MACRO(OP_RTNN) \
	MACRO(OP_RTNV) \
	MACRO(OP_JUMP) \
	MACRO(OP_JUMP_IF) \
	MACRO(OP_COPY) \
	MACRO(OP_COPY_UP) \
	MACRO(OP_COPY_DN) \
	MACRO(OP_LOAD_NONE) \
	MACRO(OP_LOAD_TRUE) \
	MACRO(OP_LOAD_FALSE) \
	MACRO(OP_LOAD_NUM) \
	MACRO(OP_LOAD_STR) \
	MACRO(OP_LOAD_ENUM) \
	MACRO(OP_OUT) \
	MACRO(OP_INC) \
	MACRO(OP_DEC) \
	MACRO(OP_NEG) \
	MACRO(OP_NOT) \
	MACRO(OP_ADD) \
	MACRO(OP_SUB) \
	MACRO(OP_MUL) \
	MACRO(OP_DIV) \
	MACRO(OP_REM) \
	MACRO(OP_EQLA) \
	MACRO(OP_EQLN) \
	MACRO(OP_LESS_THN) \
	MACRO(OP_LESS_EQL) \
	MACRO(OP_AND) \
	MACRO(OP_OR) \
	MACRO(OP_AS_STR) \


